#!/usr/bin/env bash
# Rebuilds view3d.js, the 3D road view plus the parts of three.js it uses, from src/view3d.js.
# Needs node + npm. The output is committed, so running the launcher needs neither.
set -euo pipefail
cd "$(dirname "$0")"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
(cd "$tmp" && npm init -y >/dev/null && npm install --silent three@0.186.1 esbuild@0.25)
NODE_PATH="$tmp/node_modules" "$tmp/node_modules/.bin/esbuild" src/view3d.js --bundle --minify --format=iife \
  --global-name=MazdaView3D --legal-comments=eof --target=es2020 --outfile=view3d.js \
  --banner:js="/* Mazda sim 3D road view. Generated by build.sh from src/view3d.js; includes three.js r186 (MIT, https://threejs.org). */"
echo "built $(wc -c < view3d.js) bytes"
